///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CountriesDataBZ {
/*
{
  "country": "Belize",
  "region": "Central America"
} 
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBZ({
    this.country,
    this.region,
  });
  CountriesDataBZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataVN {
/*
{
  "country": "Viet Nam",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataVN({
    this.country,
    this.region,
  });
  CountriesDataVN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataUZ {
/*
{
  "country": "Uzbekistan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataUZ({
    this.country,
    this.region,
  });
  CountriesDataUZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTM {
/*
{
  "country": "Turkmenistan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTM({
    this.country,
    this.region,
  });
  CountriesDataTM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTL {
/*
{
  "country": "Timor-Leste",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTL({
    this.country,
    this.region,
  });
  CountriesDataTL.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTH {
/*
{
  "country": "Thailand",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTH({
    this.country,
    this.region,
  });
  CountriesDataTH.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTJ {
/*
{
  "country": "Tajikistan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTJ({
    this.country,
    this.region,
  });
  CountriesDataTJ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTW {
/*
{
  "country": "Taiwan (Province of China)",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTW({
    this.country,
    this.region,
  });
  CountriesDataTW.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataLK {
/*
{
  "country": "Sri Lanka",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataLK({
    this.country,
    this.region,
  });
  CountriesDataLK.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSG {
/*
{
  "country": "Singapore",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSG({
    this.country,
    this.region,
  });
  CountriesDataSG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataPH {
/*
{
  "country": "Philippines (the)",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataPH({
    this.country,
    this.region,
  });
  CountriesDataPH.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataPK {
/*
{
  "country": "Pakistan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataPK({
    this.country,
    this.region,
  });
  CountriesDataPK.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataNP {
/*
{
  "country": "Nepal",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataNP({
    this.country,
    this.region,
  });
  CountriesDataNP.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMM {
/*
{
  "country": "Myanmar",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMM({
    this.country,
    this.region,
  });
  CountriesDataMM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMN {
/*
{
  "country": "Mongolia",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMN({
    this.country,
    this.region,
  });
  CountriesDataMN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMV {
/*
{
  "country": "Maldives",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMV({
    this.country,
    this.region,
  });
  CountriesDataMV.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMY {
/*
{
  "country": "Malaysia",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMY({
    this.country,
    this.region,
  });
  CountriesDataMY.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMO {
/*
{
  "country": "Macao",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMO({
    this.country,
    this.region,
  });
  CountriesDataMO.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataLA {
/*
{
  "country": "Lao People's Democratic Republic (the)",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataLA({
    this.country,
    this.region,
  });
  CountriesDataLA.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKG {
/*
{
  "country": "Kyrgyzstan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKG({
    this.country,
    this.region,
  });
  CountriesDataKG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKR {
/*
{
  "country": "Korea (the Republic of)",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKR({
    this.country,
    this.region,
  });
  CountriesDataKR.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKP {
/*
{
  "country": "Korea (the Democratic People's Republic of)",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKP({
    this.country,
    this.region,
  });
  CountriesDataKP.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKZ {
/*
{
  "country": "Kazakhstan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKZ({
    this.country,
    this.region,
  });
  CountriesDataKZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataJP {
/*
{
  "country": "Japan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataJP({
    this.country,
    this.region,
  });
  CountriesDataJP.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataID {
/*
{
  "country": "Indonesia",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataID({
    this.country,
    this.region,
  });
  CountriesDataID.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataIN {
/*
{
  "country": "India",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataIN({
    this.country,
    this.region,
  });
  CountriesDataIN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataHK {
/*
{
  "country": "Hong Kong",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataHK({
    this.country,
    this.region,
  });
  CountriesDataHK.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGE {
/*
{
  "country": "Georgia",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGE({
    this.country,
    this.region,
  });
  CountriesDataGE.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCN {
/*
{
  "country": "China",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCN({
    this.country,
    this.region,
  });
  CountriesDataCN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKH {
/*
{
  "country": "Cambodia",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKH({
    this.country,
    this.region,
  });
  CountriesDataKH.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBN {
/*
{
  "country": "Brunei Darussalam",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBN({
    this.country,
    this.region,
  });
  CountriesDataBN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataIO {
/*
{
  "country": "British Indian Ocean Territory (the)",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataIO({
    this.country,
    this.region,
  });
  CountriesDataIO.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBT {
/*
{
  "country": "Bhutan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBT({
    this.country,
    this.region,
  });
  CountriesDataBT.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBD {
/*
{
  "country": "Bangladesh",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBD({
    this.country,
    this.region,
  });
  CountriesDataBD.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataAZ {
/*
{
  "country": "Azerbaijan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataAZ({
    this.country,
    this.region,
  });
  CountriesDataAZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataAM {
/*
{
  "country": "Armenia",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataAM({
    this.country,
    this.region,
  });
  CountriesDataAM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataAF {
/*
{
  "country": "Afghanistan",
  "region": "Asia"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataAF({
    this.country,
    this.region,
  });
  CountriesDataAF.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGS {
/*
{
  "country": "South Georgia and the South Sandwich Islands",
  "region": "Antarctic"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGS({
    this.country,
    this.region,
  });
  CountriesDataGS.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataHM {
/*
{
  "country": "Heard Island and McDonald Islands",
  "region": "Antarctic"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataHM({
    this.country,
    this.region,
  });
  CountriesDataHM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTF {
/*
{
  "country": "French Southern Territories (the)",
  "region": "Antarctic"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTF({
    this.country,
    this.region,
  });
  CountriesDataTF.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBV {
/*
{
  "country": "Bouvet Island",
  "region": "Antarctic"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBV({
    this.country,
    this.region,
  });
  CountriesDataBV.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataAQ {
/*
{
  "country": "Antarctica",
  "region": "Antarctic"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataAQ({
    this.country,
    this.region,
  });
  CountriesDataAQ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataZW {
/*
{
  "country": "Zimbabwe",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataZW({
    this.country,
    this.region,
  });
  CountriesDataZW.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataZM {
/*
{
  "country": "Zambia",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataZM({
    this.country,
    this.region,
  });
  CountriesDataZM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataEH {
/*
{
  "country": "Western Sahara*",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataEH({
    this.country,
    this.region,
  });
  CountriesDataEH.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataUG {
/*
{
  "country": "Uganda",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataUG({
    this.country,
    this.region,
  });
  CountriesDataUG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTN {
/*
{
  "country": "Tunisia",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTN({
    this.country,
    this.region,
  });
  CountriesDataTN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTG {
/*
{
  "country": "Togo",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTG({
    this.country,
    this.region,
  });
  CountriesDataTG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTZ {
/*
{
  "country": "Tanzania, the United Republic of",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTZ({
    this.country,
    this.region,
  });
  CountriesDataTZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSD {
/*
{
  "country": "Sudan (the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSD({
    this.country,
    this.region,
  });
  CountriesDataSD.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSS {
/*
{
  "country": "South Sudan",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSS({
    this.country,
    this.region,
  });
  CountriesDataSS.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataZA {
/*
{
  "country": "South Africa",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataZA({
    this.country,
    this.region,
  });
  CountriesDataZA.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSO {
/*
{
  "country": "Somalia",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSO({
    this.country,
    this.region,
  });
  CountriesDataSO.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSL {
/*
{
  "country": "Sierra Leone",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSL({
    this.country,
    this.region,
  });
  CountriesDataSL.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSC {
/*
{
  "country": "Seychelles",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSC({
    this.country,
    this.region,
  });
  CountriesDataSC.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSN {
/*
{
  "country": "Senegal",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSN({
    this.country,
    this.region,
  });
  CountriesDataSN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataST {
/*
{
  "country": "Sao Tome and Principe",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataST({
    this.country,
    this.region,
  });
  CountriesDataST.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSH {
/*
{
  "country": "Saint Helena, Ascension and Tristan da Cunha",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSH({
    this.country,
    this.region,
  });
  CountriesDataSH.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataRW {
/*
{
  "country": "Rwanda",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataRW({
    this.country,
    this.region,
  });
  CountriesDataRW.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataRE {
/*
{
  "country": "Réunion",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataRE({
    this.country,
    this.region,
  });
  CountriesDataRE.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataNG {
/*
{
  "country": "Nigeria",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataNG({
    this.country,
    this.region,
  });
  CountriesDataNG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataNE {
/*
{
  "country": "Niger (the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataNE({
    this.country,
    this.region,
  });
  CountriesDataNE.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataNA {
/*
{
  "country": "Namibia",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataNA({
    this.country,
    this.region,
  });
  CountriesDataNA.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMZ {
/*
{
  "country": "Mozambique",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMZ({
    this.country,
    this.region,
  });
  CountriesDataMZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMA {
/*
{
  "country": "Morocco",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMA({
    this.country,
    this.region,
  });
  CountriesDataMA.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataYT {
/*
{
  "country": "Mayotte",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataYT({
    this.country,
    this.region,
  });
  CountriesDataYT.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMU {
/*
{
  "country": "Mauritius",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMU({
    this.country,
    this.region,
  });
  CountriesDataMU.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMR {
/*
{
  "country": "Mauritania",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMR({
    this.country,
    this.region,
  });
  CountriesDataMR.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataML {
/*
{
  "country": "Mali",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataML({
    this.country,
    this.region,
  });
  CountriesDataML.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMW {
/*
{
  "country": "Malawi",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMW({
    this.country,
    this.region,
  });
  CountriesDataMW.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataMG {
/*
{
  "country": "Madagascar",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataMG({
    this.country,
    this.region,
  });
  CountriesDataMG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataLY {
/*
{
  "country": "Libya",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataLY({
    this.country,
    this.region,
  });
  CountriesDataLY.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataLR {
/*
{
  "country": "Liberia",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataLR({
    this.country,
    this.region,
  });
  CountriesDataLR.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataLS {
/*
{
  "country": "Lesotho",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataLS({
    this.country,
    this.region,
  });
  CountriesDataLS.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKE {
/*
{
  "country": "Kenya",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKE({
    this.country,
    this.region,
  });
  CountriesDataKE.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGW {
/*
{
  "country": "Guinea-Bissau",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGW({
    this.country,
    this.region,
  });
  CountriesDataGW.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGN {
/*
{
  "country": "Guinea",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGN({
    this.country,
    this.region,
  });
  CountriesDataGN.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGH {
/*
{
  "country": "Ghana",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGH({
    this.country,
    this.region,
  });
  CountriesDataGH.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGM {
/*
{
  "country": "Gambia (the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGM({
    this.country,
    this.region,
  });
  CountriesDataGM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGA {
/*
{
  "country": "Gabon",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGA({
    this.country,
    this.region,
  });
  CountriesDataGA.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataET {
/*
{
  "country": "Ethiopia",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataET({
    this.country,
    this.region,
  });
  CountriesDataET.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataSZ {
/*
{
  "country": "Eswatini",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataSZ({
    this.country,
    this.region,
  });
  CountriesDataSZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataER {
/*
{
  "country": "Eritrea",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataER({
    this.country,
    this.region,
  });
  CountriesDataER.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataGQ {
/*
{
  "country": "Equatorial Guinea",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataGQ({
    this.country,
    this.region,
  });
  CountriesDataGQ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataEG {
/*
{
  "country": "Egypt",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataEG({
    this.country,
    this.region,
  });
  CountriesDataEG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataDJ {
/*
{
  "country": "Djibouti",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataDJ({
    this.country,
    this.region,
  });
  CountriesDataDJ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCI {
/*
{
  "country": "Côte d'Ivoire",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCI({
    this.country,
    this.region,
  });
  CountriesDataCI.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCG {
/*
{
  "country": "Congo (the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCG({
    this.country,
    this.region,
  });
  CountriesDataCG.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCD {
/*
{
  "country": "Congo (the Democratic Republic of the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCD({
    this.country,
    this.region,
  });
  CountriesDataCD.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataKM {
/*
{
  "country": "Comoros (the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataKM({
    this.country,
    this.region,
  });
  CountriesDataKM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataTD {
/*
{
  "country": "Chad",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataTD({
    this.country,
    this.region,
  });
  CountriesDataTD.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCF {
/*
{
  "country": "Central African Republic (the)",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCF({
    this.country,
    this.region,
  });
  CountriesDataCF.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCM {
/*
{
  "country": "Cameroon",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCM({
    this.country,
    this.region,
  });
  CountriesDataCM.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataCV {
/*
{
  "country": "Cabo Verde",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataCV({
    this.country,
    this.region,
  });
  CountriesDataCV.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBI {
/*
{
  "country": "Burundi",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBI({
    this.country,
    this.region,
  });
  CountriesDataBI.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBF {
/*
{
  "country": "Burkina Faso",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBF({
    this.country,
    this.region,
  });
  CountriesDataBF.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBW {
/*
{
  "country": "Botswana",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBW({
    this.country,
    this.region,
  });
  CountriesDataBW.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataBJ {
/*
{
  "country": "Benin",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataBJ({
    this.country,
    this.region,
  });
  CountriesDataBJ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataAO {
/*
{
  "country": "Angola",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataAO({
    this.country,
    this.region,
  });
  CountriesDataAO.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesDataDZ {
/*
{
  "country": "Algeria",
  "region": "Africa"
}
*/

  String? country;
  String? region;
  Map<String, dynamic> __origJson = {};

  CountriesDataDZ({
    this.country,
    this.region,
  });
  CountriesDataDZ.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    country = json['country']?.toString();
    region = json['region']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['region'] = region;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CountriesData {
/*
{
  "DZ": {
    "country": "Algeria",
    "region": "Africa"
  },
  "AO": {
    "country": "Angola",
    "region": "Africa"
  },
  "BJ": {
    "country": "Benin",
    "region": "Africa"
  },
  "BW": {
    "country": "Botswana",
    "region": "Africa"
  },
  "BF": {
    "country": "Burkina Faso",
    "region": "Africa"
  },
  "BI": {
    "country": "Burundi",
    "region": "Africa"
  },
  "CV": {
    "country": "Cabo Verde",
    "region": "Africa"
  },
  "CM": {
    "country": "Cameroon",
    "region": "Africa"
  },
  "CF": {
    "country": "Central African Republic (the)",
    "region": "Africa"
  },
  "TD": {
    "country": "Chad",
    "region": "Africa"
  },
  "KM": {
    "country": "Comoros (the)",
    "region": "Africa"
  },
  "CD": {
    "country": "Congo (the Democratic Republic of the)",
    "region": "Africa"
  },
  "CG": {
    "country": "Congo (the)",
    "region": "Africa"
  },
  "CI": {
    "country": "Côte d'Ivoire",
    "region": "Africa"
  },
  "DJ": {
    "country": "Djibouti",
    "region": "Africa"
  },
  "EG": {
    "country": "Egypt",
    "region": "Africa"
  },
  "GQ": {
    "country": "Equatorial Guinea",
    "region": "Africa"
  },
  "ER": {
    "country": "Eritrea",
    "region": "Africa"
  },
  "SZ": {
    "country": "Eswatini",
    "region": "Africa"
  },
  "ET": {
    "country": "Ethiopia",
    "region": "Africa"
  },
  "GA": {
    "country": "Gabon",
    "region": "Africa"
  },
  "GM": {
    "country": "Gambia (the)",
    "region": "Africa"
  },
  "GH": {
    "country": "Ghana",
    "region": "Africa"
  },
  "GN": {
    "country": "Guinea",
    "region": "Africa"
  },
  "GW": {
    "country": "Guinea-Bissau",
    "region": "Africa"
  },
  "KE": {
    "country": "Kenya",
    "region": "Africa"
  },
  "LS": {
    "country": "Lesotho",
    "region": "Africa"
  },
  "LR": {
    "country": "Liberia",
    "region": "Africa"
  },
  "LY": {
    "country": "Libya",
    "region": "Africa"
  },
  "MG": {
    "country": "Madagascar",
    "region": "Africa"
  },
  "MW": {
    "country": "Malawi",
    "region": "Africa"
  },
  "ML": {
    "country": "Mali",
    "region": "Africa"
  },
  "MR": {
    "country": "Mauritania",
    "region": "Africa"
  },
  "MU": {
    "country": "Mauritius",
    "region": "Africa"
  },
  "YT": {
    "country": "Mayotte",
    "region": "Africa"
  },
  "MA": {
    "country": "Morocco",
    "region": "Africa"
  },
  "MZ": {
    "country": "Mozambique",
    "region": "Africa"
  },
  "NA": {
    "country": "Namibia",
    "region": "Africa"
  },
  "NE": {
    "country": "Niger (the)",
    "region": "Africa"
  },
  "NG": {
    "country": "Nigeria",
    "region": "Africa"
  },
  "RE": {
    "country": "Réunion",
    "region": "Africa"
  },
  "RW": {
    "country": "Rwanda",
    "region": "Africa"
  },
  "SH": {
    "country": "Saint Helena, Ascension and Tristan da Cunha",
    "region": "Africa"
  },
  "ST": {
    "country": "Sao Tome and Principe",
    "region": "Africa"
  },
  "SN": {
    "country": "Senegal",
    "region": "Africa"
  },
  "SC": {
    "country": "Seychelles",
    "region": "Africa"
  },
  "SL": {
    "country": "Sierra Leone",
    "region": "Africa"
  },
  "SO": {
    "country": "Somalia",
    "region": "Africa"
  },
  "ZA": {
    "country": "South Africa",
    "region": "Africa"
  },
  "SS": {
    "country": "South Sudan",
    "region": "Africa"
  },
  "SD": {
    "country": "Sudan (the)",
    "region": "Africa"
  },
  "TZ": {
    "country": "Tanzania, the United Republic of",
    "region": "Africa"
  },
  "TG": {
    "country": "Togo",
    "region": "Africa"
  },
  "TN": {
    "country": "Tunisia",
    "region": "Africa"
  },
  "UG": {
    "country": "Uganda",
    "region": "Africa"
  },
  "EH": {
    "country": "Western Sahara*",
    "region": "Africa"
  },
  "ZM": {
    "country": "Zambia",
    "region": "Africa"
  },
  "ZW": {
    "country": "Zimbabwe",
    "region": "Africa"
  },
  "AQ": {
    "country": "Antarctica",
    "region": "Antarctic"
  },
  "BV": {
    "country": "Bouvet Island",
    "region": "Antarctic"
  },
  "TF": {
    "country": "French Southern Territories (the)",
    "region": "Antarctic"
  },
  "HM": {
    "country": "Heard Island and McDonald Islands",
    "region": "Antarctic"
  },
  "GS": {
    "country": "South Georgia and the South Sandwich Islands",
    "region": "Antarctic"
  },
  "AF": {
    "country": "Afghanistan",
    "region": "Asia"
  },
  "AM": {
    "country": "Armenia",
    "region": "Asia"
  },
  "AZ": {
    "country": "Azerbaijan",
    "region": "Asia"
  },
  "BD": {
    "country": "Bangladesh",
    "region": "Asia"
  },
  "BT": {
    "country": "Bhutan",
    "region": "Asia"
  },
  "IO": {
    "country": "British Indian Ocean Territory (the)",
    "region": "Asia"
  },
  "BN": {
    "country": "Brunei Darussalam",
    "region": "Asia"
  },
  "KH": {
    "country": "Cambodia",
    "region": "Asia"
  },
  "CN": {
    "country": "China",
    "region": "Asia"
  },
  "GE": {
    "country": "Georgia",
    "region": "Asia"
  },
  "HK": {
    "country": "Hong Kong",
    "region": "Asia"
  },
  "IN": {
    "country": "India",
    "region": "Asia"
  },
  "ID": {
    "country": "Indonesia",
    "region": "Asia"
  },
  "JP": {
    "country": "Japan",
    "region": "Asia"
  },
  "KZ": {
    "country": "Kazakhstan",
    "region": "Asia"
  },
  "KP": {
    "country": "Korea (the Democratic People's Republic of)",
    "region": "Asia"
  },
  "KR": {
    "country": "Korea (the Republic of)",
    "region": "Asia"
  },
  "KG": {
    "country": "Kyrgyzstan",
    "region": "Asia"
  },
  "LA": {
    "country": "Lao People's Democratic Republic (the)",
    "region": "Asia"
  },
  "MO": {
    "country": "Macao",
    "region": "Asia"
  },
  "MY": {
    "country": "Malaysia",
    "region": "Asia"
  },
  "MV": {
    "country": "Maldives",
    "region": "Asia"
  },
  "MN": {
    "country": "Mongolia",
    "region": "Asia"
  },
  "MM": {
    "country": "Myanmar",
    "region": "Asia"
  },
  "NP": {
    "country": "Nepal",
    "region": "Asia"
  },
  "PK": {
    "country": "Pakistan",
    "region": "Asia"
  },
  "PH": {
    "country": "Philippines (the)",
    "region": "Asia"
  },
  "SG": {
    "country": "Singapore",
    "region": "Asia"
  },
  "LK": {
    "country": "Sri Lanka",
    "region": "Asia"
  },
  "TW": {
    "country": "Taiwan (Province of China)",
    "region": "Asia"
  },
  "TJ": {
    "country": "Tajikistan",
    "region": "Asia"
  },
  "TH": {
    "country": "Thailand",
    "region": "Asia"
  },
  "TL": {
    "country": "Timor-Leste",
    "region": "Asia"
  },
  "TM": {
    "country": "Turkmenistan",
    "region": "Asia"
  },
  "UZ": {
    "country": "Uzbekistan",
    "region": "Asia"
  },
  "VN": {
    "country": "Viet Nam",
    "region": "Asia"
  },
  "BZ": {
    "country": "Belize",
    "region": "Central America"
  }
}
*/

  CountriesDataDZ? DZ;
  CountriesDataAO? AO;
  CountriesDataBJ? BJ;
  CountriesDataBW? BW;
  CountriesDataBF? BF;
  CountriesDataBI? BI;
  CountriesDataCV? CV;
  CountriesDataCM? CM;
  CountriesDataCF? CF;
  CountriesDataTD? TD;
  CountriesDataKM? KM;
  CountriesDataCD? CD;
  CountriesDataCG? CG;
  CountriesDataCI? CI;
  CountriesDataDJ? DJ;
  CountriesDataEG? EG;
  CountriesDataGQ? GQ;
  CountriesDataER? ER;
  CountriesDataSZ? SZ;
  CountriesDataET? ET;
  CountriesDataGA? GA;
  CountriesDataGM? GM;
  CountriesDataGH? GH;
  CountriesDataGN? GN;
  CountriesDataGW? GW;
  CountriesDataKE? KE;
  CountriesDataLS? LS;
  CountriesDataLR? LR;
  CountriesDataLY? LY;
  CountriesDataMG? MG;
  CountriesDataMW? MW;
  CountriesDataML? ML;
  CountriesDataMR? MR;
  CountriesDataMU? MU;
  CountriesDataYT? YT;
  CountriesDataMA? MA;
  CountriesDataMZ? MZ;
  CountriesDataNA? NA;
  CountriesDataNE? NE;
  CountriesDataNG? NG;
  CountriesDataRE? RE;
  CountriesDataRW? RW;
  CountriesDataSH? SH;
  CountriesDataST? ST;
  CountriesDataSN? SN;
  CountriesDataSC? SC;
  CountriesDataSL? SL;
  CountriesDataSO? SO;
  CountriesDataZA? ZA;
  CountriesDataSS? SS;
  CountriesDataSD? SD;
  CountriesDataTZ? TZ;
  CountriesDataTG? TG;
  CountriesDataTN? TN;
  CountriesDataUG? UG;
  CountriesDataEH? EH;
  CountriesDataZM? ZM;
  CountriesDataZW? ZW;
  CountriesDataAQ? AQ;
  CountriesDataBV? BV;
  CountriesDataTF? TF;
  CountriesDataHM? HM;
  CountriesDataGS? GS;
  CountriesDataAF? AF;
  CountriesDataAM? AM;
  CountriesDataAZ? AZ;
  CountriesDataBD? BD;
  CountriesDataBT? BT;
  CountriesDataIO? IO;
  CountriesDataBN? BN;
  CountriesDataKH? KH;
  CountriesDataCN? CN;
  CountriesDataGE? GE;
  CountriesDataHK? HK;
  CountriesDataIN? IN;
  CountriesDataID? ID;
  CountriesDataJP? JP;
  CountriesDataKZ? KZ;
  CountriesDataKP? KP;
  CountriesDataKR? KR;
  CountriesDataKG? KG;
  CountriesDataLA? LA;
  CountriesDataMO? MO;
  CountriesDataMY? MY;
  CountriesDataMV? MV;
  CountriesDataMN? MN;
  CountriesDataMM? MM;
  CountriesDataNP? NP;
  CountriesDataPK? PK;
  CountriesDataPH? PH;
  CountriesDataSG? SG;
  CountriesDataLK? LK;
  CountriesDataTW? TW;
  CountriesDataTJ? TJ;
  CountriesDataTH? TH;
  CountriesDataTL? TL;
  CountriesDataTM? TM;
  CountriesDataUZ? UZ;
  CountriesDataVN? VN;
  CountriesDataBZ? BZ;
  Map<String, dynamic> __origJson = {};

  CountriesData({
    this.DZ,
    this.AO,
    this.BJ,
    this.BW,
    this.BF,
    this.BI,
    this.CV,
    this.CM,
    this.CF,
    this.TD,
    this.KM,
    this.CD,
    this.CG,
    this.CI,
    this.DJ,
    this.EG,
    this.GQ,
    this.ER,
    this.SZ,
    this.ET,
    this.GA,
    this.GM,
    this.GH,
    this.GN,
    this.GW,
    this.KE,
    this.LS,
    this.LR,
    this.LY,
    this.MG,
    this.MW,
    this.ML,
    this.MR,
    this.MU,
    this.YT,
    this.MA,
    this.MZ,
    this.NA,
    this.NE,
    this.NG,
    this.RE,
    this.RW,
    this.SH,
    this.ST,
    this.SN,
    this.SC,
    this.SL,
    this.SO,
    this.ZA,
    this.SS,
    this.SD,
    this.TZ,
    this.TG,
    this.TN,
    this.UG,
    this.EH,
    this.ZM,
    this.ZW,
    this.AQ,
    this.BV,
    this.TF,
    this.HM,
    this.GS,
    this.AF,
    this.AM,
    this.AZ,
    this.BD,
    this.BT,
    this.IO,
    this.BN,
    this.KH,
    this.CN,
    this.GE,
    this.HK,
    this.IN,
    this.ID,
    this.JP,
    this.KZ,
    this.KP,
    this.KR,
    this.KG,
    this.LA,
    this.MO,
    this.MY,
    this.MV,
    this.MN,
    this.MM,
    this.NP,
    this.PK,
    this.PH,
    this.SG,
    this.LK,
    this.TW,
    this.TJ,
    this.TH,
    this.TL,
    this.TM,
    this.UZ,
    this.VN,
    this.BZ,
  });
  CountriesData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    DZ = (json['DZ'] != null) ? CountriesDataDZ.fromJson(json['DZ']) : null;
    AO = (json['AO'] != null) ? CountriesDataAO.fromJson(json['AO']) : null;
    BJ = (json['BJ'] != null) ? CountriesDataBJ.fromJson(json['BJ']) : null;
    BW = (json['BW'] != null) ? CountriesDataBW.fromJson(json['BW']) : null;
    BF = (json['BF'] != null) ? CountriesDataBF.fromJson(json['BF']) : null;
    BI = (json['BI'] != null) ? CountriesDataBI.fromJson(json['BI']) : null;
    CV = (json['CV'] != null) ? CountriesDataCV.fromJson(json['CV']) : null;
    CM = (json['CM'] != null) ? CountriesDataCM.fromJson(json['CM']) : null;
    CF = (json['CF'] != null) ? CountriesDataCF.fromJson(json['CF']) : null;
    TD = (json['TD'] != null) ? CountriesDataTD.fromJson(json['TD']) : null;
    KM = (json['KM'] != null) ? CountriesDataKM.fromJson(json['KM']) : null;
    CD = (json['CD'] != null) ? CountriesDataCD.fromJson(json['CD']) : null;
    CG = (json['CG'] != null) ? CountriesDataCG.fromJson(json['CG']) : null;
    CI = (json['CI'] != null) ? CountriesDataCI.fromJson(json['CI']) : null;
    DJ = (json['DJ'] != null) ? CountriesDataDJ.fromJson(json['DJ']) : null;
    EG = (json['EG'] != null) ? CountriesDataEG.fromJson(json['EG']) : null;
    GQ = (json['GQ'] != null) ? CountriesDataGQ.fromJson(json['GQ']) : null;
    ER = (json['ER'] != null) ? CountriesDataER.fromJson(json['ER']) : null;
    SZ = (json['SZ'] != null) ? CountriesDataSZ.fromJson(json['SZ']) : null;
    ET = (json['ET'] != null) ? CountriesDataET.fromJson(json['ET']) : null;
    GA = (json['GA'] != null) ? CountriesDataGA.fromJson(json['GA']) : null;
    GM = (json['GM'] != null) ? CountriesDataGM.fromJson(json['GM']) : null;
    GH = (json['GH'] != null) ? CountriesDataGH.fromJson(json['GH']) : null;
    GN = (json['GN'] != null) ? CountriesDataGN.fromJson(json['GN']) : null;
    GW = (json['GW'] != null) ? CountriesDataGW.fromJson(json['GW']) : null;
    KE = (json['KE'] != null) ? CountriesDataKE.fromJson(json['KE']) : null;
    LS = (json['LS'] != null) ? CountriesDataLS.fromJson(json['LS']) : null;
    LR = (json['LR'] != null) ? CountriesDataLR.fromJson(json['LR']) : null;
    LY = (json['LY'] != null) ? CountriesDataLY.fromJson(json['LY']) : null;
    MG = (json['MG'] != null) ? CountriesDataMG.fromJson(json['MG']) : null;
    MW = (json['MW'] != null) ? CountriesDataMW.fromJson(json['MW']) : null;
    ML = (json['ML'] != null) ? CountriesDataML.fromJson(json['ML']) : null;
    MR = (json['MR'] != null) ? CountriesDataMR.fromJson(json['MR']) : null;
    MU = (json['MU'] != null) ? CountriesDataMU.fromJson(json['MU']) : null;
    YT = (json['YT'] != null) ? CountriesDataYT.fromJson(json['YT']) : null;
    MA = (json['MA'] != null) ? CountriesDataMA.fromJson(json['MA']) : null;
    MZ = (json['MZ'] != null) ? CountriesDataMZ.fromJson(json['MZ']) : null;
    NA = (json['NA'] != null) ? CountriesDataNA.fromJson(json['NA']) : null;
    NE = (json['NE'] != null) ? CountriesDataNE.fromJson(json['NE']) : null;
    NG = (json['NG'] != null) ? CountriesDataNG.fromJson(json['NG']) : null;
    RE = (json['RE'] != null) ? CountriesDataRE.fromJson(json['RE']) : null;
    RW = (json['RW'] != null) ? CountriesDataRW.fromJson(json['RW']) : null;
    SH = (json['SH'] != null) ? CountriesDataSH.fromJson(json['SH']) : null;
    ST = (json['ST'] != null) ? CountriesDataST.fromJson(json['ST']) : null;
    SN = (json['SN'] != null) ? CountriesDataSN.fromJson(json['SN']) : null;
    SC = (json['SC'] != null) ? CountriesDataSC.fromJson(json['SC']) : null;
    SL = (json['SL'] != null) ? CountriesDataSL.fromJson(json['SL']) : null;
    SO = (json['SO'] != null) ? CountriesDataSO.fromJson(json['SO']) : null;
    ZA = (json['ZA'] != null) ? CountriesDataZA.fromJson(json['ZA']) : null;
    SS = (json['SS'] != null) ? CountriesDataSS.fromJson(json['SS']) : null;
    SD = (json['SD'] != null) ? CountriesDataSD.fromJson(json['SD']) : null;
    TZ = (json['TZ'] != null) ? CountriesDataTZ.fromJson(json['TZ']) : null;
    TG = (json['TG'] != null) ? CountriesDataTG.fromJson(json['TG']) : null;
    TN = (json['TN'] != null) ? CountriesDataTN.fromJson(json['TN']) : null;
    UG = (json['UG'] != null) ? CountriesDataUG.fromJson(json['UG']) : null;
    EH = (json['EH'] != null) ? CountriesDataEH.fromJson(json['EH']) : null;
    ZM = (json['ZM'] != null) ? CountriesDataZM.fromJson(json['ZM']) : null;
    ZW = (json['ZW'] != null) ? CountriesDataZW.fromJson(json['ZW']) : null;
    AQ = (json['AQ'] != null) ? CountriesDataAQ.fromJson(json['AQ']) : null;
    BV = (json['BV'] != null) ? CountriesDataBV.fromJson(json['BV']) : null;
    TF = (json['TF'] != null) ? CountriesDataTF.fromJson(json['TF']) : null;
    HM = (json['HM'] != null) ? CountriesDataHM.fromJson(json['HM']) : null;
    GS = (json['GS'] != null) ? CountriesDataGS.fromJson(json['GS']) : null;
    AF = (json['AF'] != null) ? CountriesDataAF.fromJson(json['AF']) : null;
    AM = (json['AM'] != null) ? CountriesDataAM.fromJson(json['AM']) : null;
    AZ = (json['AZ'] != null) ? CountriesDataAZ.fromJson(json['AZ']) : null;
    BD = (json['BD'] != null) ? CountriesDataBD.fromJson(json['BD']) : null;
    BT = (json['BT'] != null) ? CountriesDataBT.fromJson(json['BT']) : null;
    IO = (json['IO'] != null) ? CountriesDataIO.fromJson(json['IO']) : null;
    BN = (json['BN'] != null) ? CountriesDataBN.fromJson(json['BN']) : null;
    KH = (json['KH'] != null) ? CountriesDataKH.fromJson(json['KH']) : null;
    CN = (json['CN'] != null) ? CountriesDataCN.fromJson(json['CN']) : null;
    GE = (json['GE'] != null) ? CountriesDataGE.fromJson(json['GE']) : null;
    HK = (json['HK'] != null) ? CountriesDataHK.fromJson(json['HK']) : null;
    IN = (json['IN'] != null) ? CountriesDataIN.fromJson(json['IN']) : null;
    ID = (json['ID'] != null) ? CountriesDataID.fromJson(json['ID']) : null;
    JP = (json['JP'] != null) ? CountriesDataJP.fromJson(json['JP']) : null;
    KZ = (json['KZ'] != null) ? CountriesDataKZ.fromJson(json['KZ']) : null;
    KP = (json['KP'] != null) ? CountriesDataKP.fromJson(json['KP']) : null;
    KR = (json['KR'] != null) ? CountriesDataKR.fromJson(json['KR']) : null;
    KG = (json['KG'] != null) ? CountriesDataKG.fromJson(json['KG']) : null;
    LA = (json['LA'] != null) ? CountriesDataLA.fromJson(json['LA']) : null;
    MO = (json['MO'] != null) ? CountriesDataMO.fromJson(json['MO']) : null;
    MY = (json['MY'] != null) ? CountriesDataMY.fromJson(json['MY']) : null;
    MV = (json['MV'] != null) ? CountriesDataMV.fromJson(json['MV']) : null;
    MN = (json['MN'] != null) ? CountriesDataMN.fromJson(json['MN']) : null;
    MM = (json['MM'] != null) ? CountriesDataMM.fromJson(json['MM']) : null;
    NP = (json['NP'] != null) ? CountriesDataNP.fromJson(json['NP']) : null;
    PK = (json['PK'] != null) ? CountriesDataPK.fromJson(json['PK']) : null;
    PH = (json['PH'] != null) ? CountriesDataPH.fromJson(json['PH']) : null;
    SG = (json['SG'] != null) ? CountriesDataSG.fromJson(json['SG']) : null;
    LK = (json['LK'] != null) ? CountriesDataLK.fromJson(json['LK']) : null;
    TW = (json['TW'] != null) ? CountriesDataTW.fromJson(json['TW']) : null;
    TJ = (json['TJ'] != null) ? CountriesDataTJ.fromJson(json['TJ']) : null;
    TH = (json['TH'] != null) ? CountriesDataTH.fromJson(json['TH']) : null;
    TL = (json['TL'] != null) ? CountriesDataTL.fromJson(json['TL']) : null;
    TM = (json['TM'] != null) ? CountriesDataTM.fromJson(json['TM']) : null;
    UZ = (json['UZ'] != null) ? CountriesDataUZ.fromJson(json['UZ']) : null;
    VN = (json['VN'] != null) ? CountriesDataVN.fromJson(json['VN']) : null;
    BZ = (json['BZ'] != null) ? CountriesDataBZ.fromJson(json['BZ']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (DZ != null) {
      data['DZ'] = DZ!.toJson();
    }
    if (AO != null) {
      data['AO'] = AO!.toJson();
    }
    if (BJ != null) {
      data['BJ'] = BJ!.toJson();
    }
    if (BW != null) {
      data['BW'] = BW!.toJson();
    }
    if (BF != null) {
      data['BF'] = BF!.toJson();
    }
    if (BI != null) {
      data['BI'] = BI!.toJson();
    }
    if (CV != null) {
      data['CV'] = CV!.toJson();
    }
    if (CM != null) {
      data['CM'] = CM!.toJson();
    }
    if (CF != null) {
      data['CF'] = CF!.toJson();
    }
    if (TD != null) {
      data['TD'] = TD!.toJson();
    }
    if (KM != null) {
      data['KM'] = KM!.toJson();
    }
    if (CD != null) {
      data['CD'] = CD!.toJson();
    }
    if (CG != null) {
      data['CG'] = CG!.toJson();
    }
    if (CI != null) {
      data['CI'] = CI!.toJson();
    }
    if (DJ != null) {
      data['DJ'] = DJ!.toJson();
    }
    if (EG != null) {
      data['EG'] = EG!.toJson();
    }
    if (GQ != null) {
      data['GQ'] = GQ!.toJson();
    }
    if (ER != null) {
      data['ER'] = ER!.toJson();
    }
    if (SZ != null) {
      data['SZ'] = SZ!.toJson();
    }
    if (ET != null) {
      data['ET'] = ET!.toJson();
    }
    if (GA != null) {
      data['GA'] = GA!.toJson();
    }
    if (GM != null) {
      data['GM'] = GM!.toJson();
    }
    if (GH != null) {
      data['GH'] = GH!.toJson();
    }
    if (GN != null) {
      data['GN'] = GN!.toJson();
    }
    if (GW != null) {
      data['GW'] = GW!.toJson();
    }
    if (KE != null) {
      data['KE'] = KE!.toJson();
    }
    if (LS != null) {
      data['LS'] = LS!.toJson();
    }
    if (LR != null) {
      data['LR'] = LR!.toJson();
    }
    if (LY != null) {
      data['LY'] = LY!.toJson();
    }
    if (MG != null) {
      data['MG'] = MG!.toJson();
    }
    if (MW != null) {
      data['MW'] = MW!.toJson();
    }
    if (ML != null) {
      data['ML'] = ML!.toJson();
    }
    if (MR != null) {
      data['MR'] = MR!.toJson();
    }
    if (MU != null) {
      data['MU'] = MU!.toJson();
    }
    if (YT != null) {
      data['YT'] = YT!.toJson();
    }
    if (MA != null) {
      data['MA'] = MA!.toJson();
    }
    if (MZ != null) {
      data['MZ'] = MZ!.toJson();
    }
    if (NA != null) {
      data['NA'] = NA!.toJson();
    }
    if (NE != null) {
      data['NE'] = NE!.toJson();
    }
    if (NG != null) {
      data['NG'] = NG!.toJson();
    }
    if (RE != null) {
      data['RE'] = RE!.toJson();
    }
    if (RW != null) {
      data['RW'] = RW!.toJson();
    }
    if (SH != null) {
      data['SH'] = SH!.toJson();
    }
    if (ST != null) {
      data['ST'] = ST!.toJson();
    }
    if (SN != null) {
      data['SN'] = SN!.toJson();
    }
    if (SC != null) {
      data['SC'] = SC!.toJson();
    }
    if (SL != null) {
      data['SL'] = SL!.toJson();
    }
    if (SO != null) {
      data['SO'] = SO!.toJson();
    }
    if (ZA != null) {
      data['ZA'] = ZA!.toJson();
    }
    if (SS != null) {
      data['SS'] = SS!.toJson();
    }
    if (SD != null) {
      data['SD'] = SD!.toJson();
    }
    if (TZ != null) {
      data['TZ'] = TZ!.toJson();
    }
    if (TG != null) {
      data['TG'] = TG!.toJson();
    }
    if (TN != null) {
      data['TN'] = TN!.toJson();
    }
    if (UG != null) {
      data['UG'] = UG!.toJson();
    }
    if (EH != null) {
      data['EH'] = EH!.toJson();
    }
    if (ZM != null) {
      data['ZM'] = ZM!.toJson();
    }
    if (ZW != null) {
      data['ZW'] = ZW!.toJson();
    }
    if (AQ != null) {
      data['AQ'] = AQ!.toJson();
    }
    if (BV != null) {
      data['BV'] = BV!.toJson();
    }
    if (TF != null) {
      data['TF'] = TF!.toJson();
    }
    if (HM != null) {
      data['HM'] = HM!.toJson();
    }
    if (GS != null) {
      data['GS'] = GS!.toJson();
    }
    if (AF != null) {
      data['AF'] = AF!.toJson();
    }
    if (AM != null) {
      data['AM'] = AM!.toJson();
    }
    if (AZ != null) {
      data['AZ'] = AZ!.toJson();
    }
    if (BD != null) {
      data['BD'] = BD!.toJson();
    }
    if (BT != null) {
      data['BT'] = BT!.toJson();
    }
    if (IO != null) {
      data['IO'] = IO!.toJson();
    }
    if (BN != null) {
      data['BN'] = BN!.toJson();
    }
    if (KH != null) {
      data['KH'] = KH!.toJson();
    }
    if (CN != null) {
      data['CN'] = CN!.toJson();
    }
    if (GE != null) {
      data['GE'] = GE!.toJson();
    }
    if (HK != null) {
      data['HK'] = HK!.toJson();
    }
    if (IN != null) {
      data['IN'] = IN!.toJson();
    }
    if (ID != null) {
      data['ID'] = ID!.toJson();
    }
    if (JP != null) {
      data['JP'] = JP!.toJson();
    }
    if (KZ != null) {
      data['KZ'] = KZ!.toJson();
    }
    if (KP != null) {
      data['KP'] = KP!.toJson();
    }
    if (KR != null) {
      data['KR'] = KR!.toJson();
    }
    if (KG != null) {
      data['KG'] = KG!.toJson();
    }
    if (LA != null) {
      data['LA'] = LA!.toJson();
    }
    if (MO != null) {
      data['MO'] = MO!.toJson();
    }
    if (MY != null) {
      data['MY'] = MY!.toJson();
    }
    if (MV != null) {
      data['MV'] = MV!.toJson();
    }
    if (MN != null) {
      data['MN'] = MN!.toJson();
    }
    if (MM != null) {
      data['MM'] = MM!.toJson();
    }
    if (NP != null) {
      data['NP'] = NP!.toJson();
    }
    if (PK != null) {
      data['PK'] = PK!.toJson();
    }
    if (PH != null) {
      data['PH'] = PH!.toJson();
    }
    if (SG != null) {
      data['SG'] = SG!.toJson();
    }
    if (LK != null) {
      data['LK'] = LK!.toJson();
    }
    if (TW != null) {
      data['TW'] = TW!.toJson();
    }
    if (TJ != null) {
      data['TJ'] = TJ!.toJson();
    }
    if (TH != null) {
      data['TH'] = TH!.toJson();
    }
    if (TL != null) {
      data['TL'] = TL!.toJson();
    }
    if (TM != null) {
      data['TM'] = TM!.toJson();
    }
    if (UZ != null) {
      data['UZ'] = UZ!.toJson();
    }
    if (VN != null) {
      data['VN'] = VN!.toJson();
    }
    if (BZ != null) {
      data['BZ'] = BZ!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class Countries {
/*
{
  "status": "OK",
  "status-code": 200,
  "version": "1.0",
  "access": "public",
  "data": {
    "DZ": {
      "country": "Algeria",
      "region": "Africa"
    },
    "AO": {
      "country": "Angola",
      "region": "Africa"
    },
    "BJ": {
      "country": "Benin",
      "region": "Africa"
    },
    "BW": {
      "country": "Botswana",
      "region": "Africa"
    },
    "BF": {
      "country": "Burkina Faso",
      "region": "Africa"
    },
    "BI": {
      "country": "Burundi",
      "region": "Africa"
    },
    "CV": {
      "country": "Cabo Verde",
      "region": "Africa"
    },
    "CM": {
      "country": "Cameroon",
      "region": "Africa"
    },
    "CF": {
      "country": "Central African Republic (the)",
      "region": "Africa"
    },
    "TD": {
      "country": "Chad",
      "region": "Africa"
    },
    "KM": {
      "country": "Comoros (the)",
      "region": "Africa"
    },
    "CD": {
      "country": "Congo (the Democratic Republic of the)",
      "region": "Africa"
    },
    "CG": {
      "country": "Congo (the)",
      "region": "Africa"
    },
    "CI": {
      "country": "Côte d'Ivoire",
      "region": "Africa"
    },
    "DJ": {
      "country": "Djibouti",
      "region": "Africa"
    },
    "EG": {
      "country": "Egypt",
      "region": "Africa"
    },
    "GQ": {
      "country": "Equatorial Guinea",
      "region": "Africa"
    },
    "ER": {
      "country": "Eritrea",
      "region": "Africa"
    },
    "SZ": {
      "country": "Eswatini",
      "region": "Africa"
    },
    "ET": {
      "country": "Ethiopia",
      "region": "Africa"
    },
    "GA": {
      "country": "Gabon",
      "region": "Africa"
    },
    "GM": {
      "country": "Gambia (the)",
      "region": "Africa"
    },
    "GH": {
      "country": "Ghana",
      "region": "Africa"
    },
    "GN": {
      "country": "Guinea",
      "region": "Africa"
    },
    "GW": {
      "country": "Guinea-Bissau",
      "region": "Africa"
    },
    "KE": {
      "country": "Kenya",
      "region": "Africa"
    },
    "LS": {
      "country": "Lesotho",
      "region": "Africa"
    },
    "LR": {
      "country": "Liberia",
      "region": "Africa"
    },
    "LY": {
      "country": "Libya",
      "region": "Africa"
    },
    "MG": {
      "country": "Madagascar",
      "region": "Africa"
    },
    "MW": {
      "country": "Malawi",
      "region": "Africa"
    },
    "ML": {
      "country": "Mali",
      "region": "Africa"
    },
    "MR": {
      "country": "Mauritania",
      "region": "Africa"
    },
    "MU": {
      "country": "Mauritius",
      "region": "Africa"
    },
    "YT": {
      "country": "Mayotte",
      "region": "Africa"
    },
    "MA": {
      "country": "Morocco",
      "region": "Africa"
    },
    "MZ": {
      "country": "Mozambique",
      "region": "Africa"
    },
    "NA": {
      "country": "Namibia",
      "region": "Africa"
    },
    "NE": {
      "country": "Niger (the)",
      "region": "Africa"
    },
    "NG": {
      "country": "Nigeria",
      "region": "Africa"
    },
    "RE": {
      "country": "Réunion",
      "region": "Africa"
    },
    "RW": {
      "country": "Rwanda",
      "region": "Africa"
    },
    "SH": {
      "country": "Saint Helena, Ascension and Tristan da Cunha",
      "region": "Africa"
    },
    "ST": {
      "country": "Sao Tome and Principe",
      "region": "Africa"
    },
    "SN": {
      "country": "Senegal",
      "region": "Africa"
    },
    "SC": {
      "country": "Seychelles",
      "region": "Africa"
    },
    "SL": {
      "country": "Sierra Leone",
      "region": "Africa"
    },
    "SO": {
      "country": "Somalia",
      "region": "Africa"
    },
    "ZA": {
      "country": "South Africa",
      "region": "Africa"
    },
    "SS": {
      "country": "South Sudan",
      "region": "Africa"
    },
    "SD": {
      "country": "Sudan (the)",
      "region": "Africa"
    },
    "TZ": {
      "country": "Tanzania, the United Republic of",
      "region": "Africa"
    },
    "TG": {
      "country": "Togo",
      "region": "Africa"
    },
    "TN": {
      "country": "Tunisia",
      "region": "Africa"
    },
    "UG": {
      "country": "Uganda",
      "region": "Africa"
    },
    "EH": {
      "country": "Western Sahara*",
      "region": "Africa"
    },
    "ZM": {
      "country": "Zambia",
      "region": "Africa"
    },
    "ZW": {
      "country": "Zimbabwe",
      "region": "Africa"
    },
    "AQ": {
      "country": "Antarctica",
      "region": "Antarctic"
    },
    "BV": {
      "country": "Bouvet Island",
      "region": "Antarctic"
    },
    "TF": {
      "country": "French Southern Territories (the)",
      "region": "Antarctic"
    },
    "HM": {
      "country": "Heard Island and McDonald Islands",
      "region": "Antarctic"
    },
    "GS": {
      "country": "South Georgia and the South Sandwich Islands",
      "region": "Antarctic"
    },
    "AF": {
      "country": "Afghanistan",
      "region": "Asia"
    },
    "AM": {
      "country": "Armenia",
      "region": "Asia"
    },
    "AZ": {
      "country": "Azerbaijan",
      "region": "Asia"
    },
    "BD": {
      "country": "Bangladesh",
      "region": "Asia"
    },
    "BT": {
      "country": "Bhutan",
      "region": "Asia"
    },
    "IO": {
      "country": "British Indian Ocean Territory (the)",
      "region": "Asia"
    },
    "BN": {
      "country": "Brunei Darussalam",
      "region": "Asia"
    },
    "KH": {
      "country": "Cambodia",
      "region": "Asia"
    },
    "CN": {
      "country": "China",
      "region": "Asia"
    },
    "GE": {
      "country": "Georgia",
      "region": "Asia"
    },
    "HK": {
      "country": "Hong Kong",
      "region": "Asia"
    },
    "IN": {
      "country": "India",
      "region": "Asia"
    },
    "ID": {
      "country": "Indonesia",
      "region": "Asia"
    },
    "JP": {
      "country": "Japan",
      "region": "Asia"
    },
    "KZ": {
      "country": "Kazakhstan",
      "region": "Asia"
    },
    "KP": {
      "country": "Korea (the Democratic People's Republic of)",
      "region": "Asia"
    },
    "KR": {
      "country": "Korea (the Republic of)",
      "region": "Asia"
    },
    "KG": {
      "country": "Kyrgyzstan",
      "region": "Asia"
    },
    "LA": {
      "country": "Lao People's Democratic Republic (the)",
      "region": "Asia"
    },
    "MO": {
      "country": "Macao",
      "region": "Asia"
    },
    "MY": {
      "country": "Malaysia",
      "region": "Asia"
    },
    "MV": {
      "country": "Maldives",
      "region": "Asia"
    },
    "MN": {
      "country": "Mongolia",
      "region": "Asia"
    },
    "MM": {
      "country": "Myanmar",
      "region": "Asia"
    },
    "NP": {
      "country": "Nepal",
      "region": "Asia"
    },
    "PK": {
      "country": "Pakistan",
      "region": "Asia"
    },
    "PH": {
      "country": "Philippines (the)",
      "region": "Asia"
    },
    "SG": {
      "country": "Singapore",
      "region": "Asia"
    },
    "LK": {
      "country": "Sri Lanka",
      "region": "Asia"
    },
    "TW": {
      "country": "Taiwan (Province of China)",
      "region": "Asia"
    },
    "TJ": {
      "country": "Tajikistan",
      "region": "Asia"
    },
    "TH": {
      "country": "Thailand",
      "region": "Asia"
    },
    "TL": {
      "country": "Timor-Leste",
      "region": "Asia"
    },
    "TM": {
      "country": "Turkmenistan",
      "region": "Asia"
    },
    "UZ": {
      "country": "Uzbekistan",
      "region": "Asia"
    },
    "VN": {
      "country": "Viet Nam",
      "region": "Asia"
    },
    "BZ": {
      "country": "Belize",
      "region": "Central America"
    }
  }
}
*/

  String? status;
  int? statusCode;
  String? version;
  String? access;
  CountriesData? data;
  Map<String, dynamic> __origJson = {};

  Countries({
    this.status,
    this.statusCode,
    this.version,
    this.access,
    this.data,
  });
  Countries.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    status = json['status']?.toString();
    statusCode = json['status-code']?.toInt();
    version = json['version']?.toString();
    access = json['access']?.toString();
    data = (json['data'] != null) ? CountriesData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['status-code'] = statusCode;
    data['version'] = version;
    data['access'] = access;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
